POST http://localhost:9988/save
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="img.jpg"
Content-Type: image/jpeg

< ./down.jpg
--WebAppBoundary--

###

GET http://localhost:9988/file/8f90bec4-abbd-41bf-a86c-41e9744cc03b

###
